config/routes.rb
Rails.application.routes.draw do

  get 'github/index'

  root to: "users#new"
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  
  get "/orgs" => "github#orgs"
  get "/repos" => "github#repos"
  get "/pulls" => "github#pulls"
  get "/pull" => "github#pull"

end

app/models/pull_request_approval.rb
class PullRequestApproval < ActiveRecord::Base

	def self.getNumApprovals(prId)
		@votes = PullRequestApproval.where(:prId => prId).count	
	end
end

app/models/user.rb
class User < ActiveRecord::Base

 def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	helper_method :current_user
	helper_method :client
	helper_method :avatar
 
  	private
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	rescue ActiveRecord::RecordNotFound
  end 

  def client
	@client = Octokit::Client.new(:access_token => session[:at])
  end

  def avatar
	@avatar = session[:user_avatar]
  end

end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def index
  end

  def orgs
	@orgs = client.orgs
  end

  def repos
  	org =  CGI::unescape(params[:org_name])
  	@repos = client.org_repos org, {:type => 'member'}
	@repos.each do |repo|
		if repo.private === false
			repo.visibility = "Public"
		else
			repo.visibility = "Private"
		end
	end
  end

  def pulls
  	data = CGI::unescape(params[:repo])
 	repo = client.repo data
  	pulls = repo.rels[:pulls]
  	@pull_requests = pulls.get().data

	# Get the number of votes for each PR
	@pull_requests.each do |pull_request|
		numVotes = PullRequestApproval.getNumApprovals(pull_request.id)
		if (numVotes == 1)
			pull_request.statusClass = "one_vote"
		elseif (numVotes > 1) 
			pull_request.statusClass = "two_votes"
		else 
			pull_request.statusClass = "no_votes"
		end
	end
  end

  def pull
  	org =  CGI::unescape(params[:repo])
	pr = CGI::unescape(params[:pid])
	@pull = client.pull_request org,pr
	@comments = client.pull_request_comments org,pr
	@commits = client.pull_commits org,pr

	#render :text => @pull.inspect
  end
  
  def approvePullRequest
 		prID = CGI::unescape(params[:prID]) 
  end 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		auth = request.env["omniauth.auth"]
		user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
		session[:user_id] = user.id
		session[:user_data] = user
		session[:user_nick] = auth.info.nickname
		session[:user_avatar] = auth.info.image
		session[:at] = auth.credentials.token

		redirect_to root_url, :notice => "Signed in!"
  	end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def new
 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/github/index.html.erb
<h1>Github#index</h1>
<p>Find me in app/views/github/index.html.erb</p>

app/views/github/orgs.html.erb
<div class="row">
	<div class="col-lg-12">
   		<h1 class="page-header">Your Organizations</h1>
  	</div>
	<%@orgs.each do |org|%>
    	<div class="col-lg-3 col-md-4 col-xs-6 thumb">
			<%= link_to image_tag(org.avatar_url,:width => "200px"), repos_path(:org_name => org.login), :class => 'thumbnail' %>
     	</div>
	<% end %>
</div>

app/views/github/pull.html.erb
<%=@pull.diff_url %>
<hr>
<h2><%= @pull.title %></h2>
<hr>
<div class="flex-table gh-header-meta">
    <div class="flex-table-item">
        <div class="state state-open">
          <span class="octicon octicon-git-pull-request"></span>
          <%=@pull.state %>
        </div>
    </div>
    <div class="flex-table-item flex-table-item-primary">
		<a href="#" class="author pull-header-username css-truncate css-truncate-target expandable"><%=@pull.head.user.login %></a>
   		wants to merge 1 commit into
		<span class="commit-ref current-branch css-truncate user-select-contain expandable"><span class="css-truncate-target user"><%=@pull.base.repo.owner.login %></span>:<span class="css-truncate-target"><%=@pull.base.ref%></span></span>
		from
		<span class="commit-ref current-branch css-truncate user-select-contain expandable"><span class="css-truncate-target user"><%=@pull.head.repo.owner.login %></span>:<span class="css-truncate-target"><%=@pull.head.ref%></span></span>
    </div>
  </div>
<hr>
<div class="file">
	<div class="header">app/webroot/js/Manage/Views/SaveFilterActionItem.js</div>
	<ul class="diff">
		<li>console.log('callback1', arguments);</li>
		<li>self.destroyReviewalTools();</li>
		<li>self.fetch();</li>
		<li class="red"><span>-</span></li>
		<li class="freen"><span>+</span>ga('send', 'event', 'Manage - Asset Review', 'Click', 'Initialize Annotation');</li>
	</ul>
</div>

<div class="file">
	<div class="header">app/webroot/js/Manage/Views/SaveFilterActionItem.js</div>
	<ul class="diff">
		<li>console.log('callback1', arguments);</li>
		<li>self.destroyReviewalTools();</li>
		<li>self.fetch();</li>
		<li class="red"><span>-</span></li>
		<li class="freen"><span>+</span>ga('send', 'event', 'Manage - Asset Review', 'Click', 'Initialize Annotation');</li>
	</ul>
</div>

<div class="file">
	<div class="header">app/webroot/js/Manage/Views/SaveFilterActionItem.js</div>
	<ul class="diff">
		<li>console.log('callback1', arguments);</li>
		<li>self.destroyReviewalTools();</li>
		<li>self.fetch();</li>
		<li class="red"><span>-</span></li>
		<li class="freen"><span>+</span>ga('send', 'event', 'Manage - Asset Review', 'Click', 'Initialize Annotation');</li>
	</ul>
</div>

<div class="file">
	<div class="header">app/webroot/js/Manage/Views/SaveFilterActionItem.js</div>
	<ul class="diff">
		<li>console.log('callback1', arguments);</li>
		<li>self.destroyReviewalTools();</li>
		<li>self.fetch();</li>
		<li class="red"><span>-</span></li>
		<li class="freen"><span>+</span>ga('send', 'event', 'Manage - Asset Review', 'Click', 'Initialize Annotation');</li>
	</ul>
</div>

<hr>

COMMENT FEED HERE
<%=@comments%>
<% @comments.each do |comment|%>
fob
<%= comment.url%>
<% end %>
<hr>

NEW COMMENT FORM HERE
<%= @pull.inspect %>

app/views/github/pulls.html.erb
<div class="repository-with-sidebar repo-container new-discussion-timeline">
	<ul class="table-list table-list-bordered table-list-issues js-navigation-container js-active-navigation-container">
<% @pull_requests.each do |pull_request| %>
		<li id="issue_1982" class="selectable read table-list-item js-navigation-item js-issue-row <%= pull_request.statusClass %>">
			<label class="table-list-cell table-list-cell-checkbox">
     			<input type="checkbox" class="select-toggle-check js-check-all-item js-issues-list-check" name="issues[]" value="1982">
    		</label>
			<div class="table-list-cell table-list-cell-type">
    			<a href="/KSCTECHNOLOGIES/realtimeprocess-development/issues?q=is%3Apr+is%3Aopen" aria-label="View all pull requests" class="tooltipped tooltipped-n">
      				<span class="octicon octicon-git-pull-request open"></span>
				</a>
			</div>
			<div class="table-list-cell issue-title">
<%= link_to pull_request.title, pull_path(:repo => pull_request.base.repo.full_name ,:pid => pull_request.number),class: "issue-title-link js-navigation-open" %>  

     			<div class="issue-meta">
      				<span class="issue-meta-section opened-by">#<%=pull_request.number %> opened <time datetime="2015-09-30T20:07:10Z" is="relative-time" title="Sep 30, 2015, 4:07 PM EDT">6 hours ago</time> by
          				<a href="/KSCTECHNOLOGIES/realtimeprocess-development/issues?q=is%3Apr+is%3Aopen+author%3Adstewart123" aria-label="View all pull requests opened by dstewart123" class="tooltipped tooltipped-s muted-link"><%=pull_request.user.login%></a>
      				</span>
      				<span class="issue-meta-section css-truncate issue-milestone"></span>
				</div>
  			</div>
			<div class="table-list-cell table-list-cell-avatar"></div>
			<div class="table-list-cell issue-comments">
    			<a href="/KSCTECHNOLOGIES/realtimeprocess-development/pull/1982" class="muted-link "><span class="octicon octicon-comment"></span><%=pull_request.comments%></a> 4
  			</div>
		</li>
    <% end %>
  	</ul>
</div>

app/views/github/repos.html.erb
<ul>
<% @repos.each do |repo| %>

<li>
	<%= link_to repo.name, pulls_path(:repo => repo.full_name) %> <span><%=repo.visibility%></span>
</li>

<% end %>
</ul>

<% @repos %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peer Review</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">robiReview</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
			<% if current_user %>
            <li><a href="/">Home</a></li>
            <li><a href="/orgs">My Orgs</a></li>
			<% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right hidden-sm hidden-xs">
			<% if current_user %>
				<%= image_tag(avatar, size: "35x35", alt: "Edit Entry",class: "img-circle")%>
				<li class="dropdown">
          			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Welcome #{current_user.name}" %><span class="caret"></span></a>
          			<ul class="dropdown-menu">
            			<li><a href="#">Another action</a></li>
            			<li><a href="#">Separated link</a></li>
            			<li><a href="#">Something else here</a></li>
            			<li role="separator" class="divider"></li>
            			<li><a href="/signout">logout</a></li>
          			</ul>
        		</li>
			<% else %>
  				<li><form> <a href="/auth/github" class="btn btn-success navbar-btn btn-sm">Sign in with Github</a></form></li>
			<% end  %>
		</ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="starter-template">
		<%= yield %>
      </div>
    </div><!-- /.container -->
</body>
</html>